aliases = [ ]
dependencies = [
	"Object.create"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment"
spec = "https://dom.spec.whatwg.org/#interface-documentfragment"
notes = [ ]

[browsers]
android = "<3"
firefox = "<4"
ios_chr = "<4"
ios_saf = "<4"
ie = "<=11"
ie_mob = "<=11"
edge = "<17"
opera = "<11"
op_mini = "<11"
safari = "<4"
firefox_mob = "<4"
samsung_mob = "<3"

